DOT="python ../../datastruct/tree/red-black-tree/src/rbt2dot.py"

#python ../../datastruct/tree/red-black-tree/src/rbt2dot.py -o huffman-tr.dot "((((. O1 .) 2 (. R1 .)) 5 (. N3 .)) 13 (((. T2 .) 4 (. I2 .)) 8 ((. A2 .) 4 ((. E1 .) 2 (. L1 .)))))"
$DOT -o huffman-tr-v1.dot "(((. A2 .) 5 (. N3 .)) 13 ((((. L1 .) 2 (. E1 .)) 4 (. T2 .)) 8 (((. O1 .) 2 (. R1 .)) 4 (. I2 .))))"
$DOT -o huffman-tr-v2.dot "((((. O1 .) 2 (. R1 .)) 5 (. N3 .)) 13 (((. T2 .) 4 (. I2 .)) 8 ((. A2 .) 4 ((. E1 .) 2 (. L1 .)))))"
$DOT -o huffman-tr-v3.dot "((((. O1 .) 2 (. R1 .)) 5 (. N3 .)) 13 (((. A2 .) 4 (. I2 .)) 8 ((. T2 .) 4 ((. E1 .) 2 (. L1 .)))))"
# python ../../datastruct/tree/red-black-tree/src/rbt2dot.py -o huffman-tr1.dot "((. E1 .) 2 (. L1 .))"
# python ../../datastruct/tree/red-black-tree/src/rbt2dot.py -o huffman-tr2.dot "((. O1 .) 2 (. R1 .))"
# python ../../datastruct/tree/red-black-tree/src/rbt2dot.py -o huffman-tr3.dot "((. T2 .) 4 (. I2 .))"
# python ../../datastruct/tree/red-black-tree/src/rbt2dot.py -o huffman-tr4.dot "((. A2 .) 4 ((. E1 .) 2 (. L1 .)))"
# python ../../datastruct/tree/red-black-tree/src/rbt2dot.py -o huffman-tr5.dot "(((. O1 .) 2 (. R1 .)) 5 (. N3 .))"
# python ../../datastruct/tree/red-black-tree/src/rbt2dot.py -o huffman-tr6.dot "(((. T2 .) 4 (. I2 .)) 8 ((. A2 .) 4 ((. E1 .) 2 (. L1 .))))"